// Generated by CoffeeScript 1.9.3
var browserSync, coffee, cssmin, gulp, gutil, jade, minifyHTML, prefix, sass, svgmin, watch;

gulp = require('gulp');

sass = require('gulp-ruby-sass');

prefix = require('gulp-autoprefixer');

cssmin = require('gulp-cssmin');

coffee = require('gulp-coffee');

jade = require('gulp-jade');

minifyHTML = require('gulp-minify-html');

svgmin = require('gulp-svgmin');

watch = require('gulp-watch');

browserSync = (require('browser-sync')).create();

gutil = require('gulp-util');

gulp.task('serve', function() {
  browserSync.init({
    server: {
      baseDir: "www/"
    }
  });
  (gulp.watch("www/*")).on("change", browserSync.reload);
  (gulp.watch("www/css/*")).on("change", browserSync.reload);
  return (gulp.watch("www/js/*")).on("change", browserSync.reload);
});

gulp.task('css', function() {
  return sass('app/css/index.sass').pipe(gulp.dest('www/css'));
});

gulp.task('coffee', function() {
  return gulp.src('app/coffee/*.coffee').pipe(coffee({
    bare: true
  }).on('error', gutil.log)).pipe(gulp.dest('www/js'));
});

gulp.task('html', function() {
  return gulp.src('app/*.jade').pipe(jade()).pipe(minifyHTML()).pipe(gulp.dest('www/'));
});

gulp.task('default', ['watch', 'serve', 'coffee', 'css', 'html']);

gulp.task('watch', function() {
  gulp.watch('app/coffee/*', ['coffee']);
  gulp.watch('app/css/*', ['css']);
  return gulp.watch('app/*.jade', ['html']);
});
